// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqK9D41E-R9GY1_xOtYM0eo-6v0kdLZyg',
    appId: '1:739235439031:web:15028973146ce9e9c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    authDomain: 'agrimarket-60402.firebaseapp.com',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    measurementId: 'G-SR4ZD7QLPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF9LKr9OJxKgbEyV_KupR68NzyDOxD10k',
    appId: '1:739235439031:android:3e8316dfd6c2c3d7c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjzYdwfdsxphdIuD6eruqg9Tvnvk1G2g',
    appId: '1:739235439031:ios:690ac822149a4859c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    iosClientId: '739235439031-7sootfh4cife177k3hb9af4tkeskubrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrimarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGjzYdwfdsxphdIuD6eruqg9Tvnvk1G2g',
    appId: '1:739235439031:ios:690ac822149a4859c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    iosClientId: '739235439031-7sootfh4cife177k3hb9af4tkeskubrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrimarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqK9D41E-R9GY1_xOtYM0eo-6v0kdLZyg',
    appId: '1:739235439031:web:f6b859eb9b4fc4d2c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    authDomain: 'agrimarket-60402.firebaseapp.com',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    measurementId: 'G-2QW71RDRNQ',
  );
}
